[('Set-Cookie',
 ['__cfduid=dd3da53df59f2cbbe3f69865a346649b51481387412; expires=Sun, 10-Dec-17 16:30:12 GMT; path=/; domain=.acf.me.uk; HttpOnly']),
('Accept-Ranges', ['bytes']),
('Server', ['cloudflare-nginx']),
('Last-Modified', ['Sat, 10 Dec 2016 16:05:37 GMT']),
('Date', ['Sat, 10 Dec 2016 16:30:13 GMT']),
('Cf-Ray', ['30f2148043ca3415-HKG']),
('Content-Type', ['application/json'])]